version: '3.8'

services:

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   environment:
  #     - VITE_SERVER_URL=http://localhost:5000
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - app
  #   networks:
  #     - fullstack

  app:
    image: hugfiles-server-backend:v0
    ports:
      - "5000:5000"
    depends_on:
      - celery

    command: ["python",  "main.py"]
    environment:
      - PORT=5000
      - FLASK_ENV=development
      - REDIS_HOST=redis-server
      - CELERY_BROKER_URL=redis://redis-server:6379/0
      - CELERY_RESULT_BACKEND=redis://redis-server:6379/1
      - UPLOAD_FOLDER=data/
      - SECRET_KEY=secret

    healthcheck:
      test: curl --fail http://localhost:5000/ || exit 1
      interval: 5s
      timeout: 1h
      retries: 5



    volumes:
      - shared_data:/app/data  # Montar el mismo volumen en la carpeta /app/data

  celery:
    image: hugfiles-server-backend:v0
    depends_on:
      - redis-server
    environment:
      - REDIS_HOST=redis-server-1
      - CELERY_BROKER_URL=redis://redis-server:6379/0
      - CELERY_RESULT_BACKEND=redis://redis-server:6379/1
      - UPLOAD_FOLDER=data/
    
    command: ["celery",  "-A", "main.celery", "worker", "--loglevel=info"]
    volumes:
      - shared_data:/app/data  



  redis-server:
    image: redis:6.2.5-alpine




networks:
  fullstack:
    driver: bridge
volumes:
  shared_data: 